import { readFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import AdmZip from 'adm-zip';
import { AppStore } from '../state/store';
import { IpaArtifact } from '../types';
import { LogService } from './log-service';
import { AppError } from '../utils/errors';
import { normalizeEntitlements, parseMobileProvisionEntitlements, parsePlistBuffer } from '../utils/plist';

const infoPlistPattern = /^Payload\/[^/]+\.app\/Info\.plist$/i;
const xcentPattern = /^Payload\/[^/]+\.app\/.*\.(xcent|entitlements)$/i;
const provisionPattern = /^Payload\/[^/]+\.app\/embedded\.mobileprovision$/i;

export class IpaService {
  constructor(
    private readonly store: AppStore,
    private readonly logs: LogService
  ) {}

  public list(): IpaArtifact[] {
    return Array.from(this.store.ipas.values()).sort(
      (a, b) => new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()
    );
  }

  public getById(id: string): IpaArtifact | undefined {
    return this.store.ipas.get(id);
  }

  public async inspectAndStore(file: { path: string; filename: string; originalname: string; size: number }): Promise<IpaArtifact> {
    const absolutePath = path.resolve(file.path);

    try {
      const buffer = await readFile(absolutePath);

      let zip: AdmZip;
      try {
        zip = new AdmZip(buffer);
      } catch {
        throw new AppError(
          'INVALID_IPA_ARCHIVE',
          'This file is not a valid IPA/ZIP archive.',
          400,
          'Export a valid .ipa file from Xcode or your CI artifact and upload again.'
        );
      }

      const entries = zip.getEntries();
      const infoEntry = entries.find((entry) => infoPlistPattern.test(entry.entryName));
      if (!infoEntry) {
        throw new AppError(
          'INFO_PLIST_NOT_FOUND',
          'Could not find Payload/<App>.app/Info.plist in the IPA.',
          400,
          'Use a standard IPA structure generated by Xcode archive/export flow.'
        );
      }

      let info: Record<string, unknown>;
      try {
        info = parsePlistBuffer(infoEntry.getData());
      } catch (error) {
        throw new AppError(
          'INFO_PLIST_PARSE_FAILED',
          `Failed to parse Info.plist: ${error instanceof Error ? error.message : String(error)}`,
          400,
          'Ensure the IPA contains a valid XML or binary Info.plist.'
        );
      }

      const xcentEntry = entries.find((entry) => xcentPattern.test(entry.entryName));
      const provisionEntry = entries.find((entry) => provisionPattern.test(entry.entryName));

      let entitlements: Record<string, unknown> = {};
      if (xcentEntry) {
        try {
          entitlements = {
            ...entitlements,
            ...normalizeEntitlements(parsePlistBuffer(xcentEntry.getData()))
          };
        } catch {
          this.logs.push({
            level: 'warn',
            code: 'XCENT_PARSE_FAILED',
            message: `Could not parse ${xcentEntry.entryName}; continuing with available data.`
          });
        }
      }

      if (provisionEntry) {
        try {
          entitlements = {
            ...entitlements,
            ...normalizeEntitlements(parseMobileProvisionEntitlements(provisionEntry.getData()))
          };
        } catch {
          this.logs.push({
            level: 'warn',
            code: 'MOBILEPROVISION_PARSE_FAILED',
            message: 'Could not parse embedded.mobileprovision; entitlement metadata may be partial.'
          });
        }
      }

      const bundleId = String(info.CFBundleIdentifier ?? 'unknown.bundle.id');
      const displayName = String(info.CFBundleDisplayName ?? info.CFBundleName ?? bundleId);
      const version = String(info.CFBundleShortVersionString ?? info.CFBundleVersion ?? '0.0.0');
      const minIOSVersion = info.MinimumOSVersion ? String(info.MinimumOSVersion) : undefined;

      const warnings: string[] = [];
      if (Object.keys(entitlements).some((key) => key.startsWith('com.apple.private.'))) {
        warnings.push('Private Apple entitlements detected; this build will fail for normal sideload signing.');
      }

      if (entitlements['get-task-allow'] === true) {
        warnings.push('Debug entitlement get-task-allow=true detected. Use release provisioning for non-dev installs.');
      }

      if (!Object.keys(entitlements).length) {
        warnings.push('No entitlements were extracted. Signing checks will rely on Info.plist only.');
      }

      const capabilities = Object.keys(entitlements)
        .filter((key) => !key.startsWith('application-identifier'))
        .sort();

      const artifact: IpaArtifact = {
        id: this.store.newId('ipa'),
        filename: file.filename,
        originalName: file.originalname,
        absolutePath,
        uploadedAt: new Date().toISOString(),
        sizeBytes: file.size,
        bundleId,
        displayName,
        version,
        minIOSVersion,
        entitlements,
        capabilities,
        warnings
      };

      this.store.saveIpa(artifact);
      this.logs.push({
        level: 'info',
        code: 'IPA_IMPORTED',
        message: `Imported ${artifact.originalName} (${artifact.bundleId})`,
        action: warnings.length
          ? 'Review IPA warnings before install, then run the helper-first install pipeline.'
          : 'Select a device and run install pipeline.'
      });

      return artifact;
    } catch (error) {
      await this.cleanupRejectedUpload(absolutePath);
      throw error;
    }
  }

  private async cleanupRejectedUpload(absolutePath: string): Promise<void> {
    try {
      await unlink(absolutePath);
    } catch (error) {
      const code =
        typeof error === 'object' && error && 'code' in error
          ? String((error as { code?: unknown }).code)
          : undefined;

      if (code === 'ENOENT') {
        return;
      }

      this.logs.push({
        level: 'warn',
        code: 'IPA_UPLOAD_CLEANUP_FAILED',
        message: `Failed to remove rejected IPA upload at ${absolutePath}.`,
        action: error instanceof Error ? error.message : String(error)
      });
    }
  }
}
